#pragma once

#include "codebuilder_defs.h"

void codebuilder_build_pop(CodeBuilder *builder);
void codebuilder_build_pop2(CodeBuilder *builder);
void codebuilder_build_dup(CodeBuilder *builder);
void codebuilder_build_dup_x1(CodeBuilder *builder);
void codebuilder_build_dup_x2(CodeBuilder *builder);
void codebuilder_build_dup2(CodeBuilder *builder);
void codebuilder_build_dup2_x1(CodeBuilder *builder);
void codebuilder_build_dup2_x2(CodeBuilder *builder);
void codebuilder_build_swap(CodeBuilder *builder);
void codebuilder_build_pop_value(CodeBuilder *builder);
void codebuilder_build_dup_value(CodeBuilder *builder);
void codebuilder_build_dup_address(CodeBuilder *builder);
void codebuilder_build_dup_value_x1(CodeBuilder *builder);
void codebuilder_build_dup_value_x2(CodeBuilder *builder);
void codebuilder_build_iadd(CodeBuilder *builder);
void codebuilder_build_ladd(CodeBuilder *builder);
void codebuilder_build_fadd(CodeBuilder *builder);
void codebuilder_build_dadd(CodeBuilder *builder);
void codebuilder_build_isub(CodeBuilder *builder);
void codebuilder_build_lsub(CodeBuilder *builder);
void codebuilder_build_fsub(CodeBuilder *builder);
void codebuilder_build_dsub(CodeBuilder *builder);
void codebuilder_build_imul(CodeBuilder *builder);
void codebuilder_build_lmul(CodeBuilder *builder);
void codebuilder_build_fmul(CodeBuilder *builder);
void codebuilder_build_dmul(CodeBuilder *builder);
void codebuilder_build_idiv(CodeBuilder *builder);
void codebuilder_build_ldiv(CodeBuilder *builder);
void codebuilder_build_fdiv(CodeBuilder *builder);
void codebuilder_build_ddiv(CodeBuilder *builder);
void codebuilder_build_irem(CodeBuilder *builder);
void codebuilder_build_lrem(CodeBuilder *builder);
void codebuilder_build_frem(CodeBuilder *builder);
void codebuilder_build_drem(CodeBuilder *builder);
void codebuilder_build_ineg(CodeBuilder *builder);
void codebuilder_build_lneg(CodeBuilder *builder);
void codebuilder_build_fneg(CodeBuilder *builder);
void codebuilder_build_dneg(CodeBuilder *builder);
void codebuilder_build_ishl(CodeBuilder *builder);
void codebuilder_build_lshl(CodeBuilder *builder);
void codebuilder_build_ishr(CodeBuilder *builder);
void codebuilder_build_lshr(CodeBuilder *builder);
void codebuilder_build_iushr(CodeBuilder *builder);
void codebuilder_build_lushr(CodeBuilder *builder);
void codebuilder_build_iand(CodeBuilder *builder);
void codebuilder_build_land(CodeBuilder *builder);
void codebuilder_build_ior(CodeBuilder *builder);
void codebuilder_build_lor(CodeBuilder *builder);
void codebuilder_build_ixor(CodeBuilder *builder);
void codebuilder_build_lxor(CodeBuilder *builder);
void codebuilder_build_iinc(CodeBuilder *builder, int local_index, int increment);
void codebuilder_build_i2l(CodeBuilder *builder);
void codebuilder_build_i2f(CodeBuilder *builder);
void codebuilder_build_i2d(CodeBuilder *builder);
void codebuilder_build_l2i(CodeBuilder *builder);
void codebuilder_build_l2f(CodeBuilder *builder);
void codebuilder_build_l2d(CodeBuilder *builder);
void codebuilder_build_f2i(CodeBuilder *builder);
void codebuilder_build_f2l(CodeBuilder *builder);
void codebuilder_build_f2d(CodeBuilder *builder);
void codebuilder_build_d2i(CodeBuilder *builder);
void codebuilder_build_d2l(CodeBuilder *builder);
void codebuilder_build_d2f(CodeBuilder *builder);
void codebuilder_build_i2b(CodeBuilder *builder);
void codebuilder_build_i2c(CodeBuilder *builder);
void codebuilder_build_i2s(CodeBuilder *builder);
void codebuilder_build_lcmp(CodeBuilder *builder);
void codebuilder_build_fcmp(CodeBuilder *builder, CmpNaN nan_behavior);
void codebuilder_build_dcmp(CodeBuilder *builder, CmpNaN nan_behavior);
