#pragma once

#include <stddef.h>

typedef struct
{
    const char *name;          /* Basename of the embedded file (e.g., "stdio.c") */
    const unsigned char *data; /* Embedded file contents */
    int size;                  /* Size of the embedded data */
} EmbeddedFile;

/* Embedded data generated by gen_embed.sh */

/* stdio.c */
extern const unsigned char embedded_stdio_data[];
extern const int embedded_stdio_size;

/* string.c */
extern const unsigned char embedded_string_data[];
extern const int embedded_string_size;

/* stddef.h */
extern const unsigned char embedded_stddef_h_data[];
extern const int embedded_stddef_h_size;

/* stdint.h */
extern const unsigned char embedded_stdint_h_data[];
extern const int embedded_stdint_h_size;

/* stdio.h */
extern const unsigned char embedded_stdio_h_data[];
extern const int embedded_stdio_h_size;

/* stdlib.h */
extern const unsigned char embedded_stdlib_h_data[];
extern const int embedded_stdlib_h_size;

/* limits.h */
extern const unsigned char embedded_limits_h_data[];
extern const int embedded_limits_h_size;

/* string.h */
extern const unsigned char embedded_string_h_data[];
extern const int embedded_string_h_size;

/* Metadata for embedded files */
extern const EmbeddedFile embedded_files[];
extern const int embedded_file_count;

/* Lookup an embedded file by basename (e.g., "stdio.c") */
const EmbeddedFile *embedded_find(const char *name);
